version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: weather_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - weather_network
  
  api:
    build: .
    container_name: skynow
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - weather_network
    command: ["uvicorn", "app.main:app","--host","0.0.0.0","--port","8000","--reload"]

volumes:
    pg_data:
      driver: local

networks:
    weather_network:
